[functions]
    directory = "functions/"
    node_bundler = "esbuild"
    included_files = ["functions/**"]
[[redirects]]
    from = "/"
    to = "/.netlify/functions/bookings"
    status = 200
[[redirects]]
    from = "/*"
    to = "/.netlify/functions/:splat"
    status = 200
